language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yo1sggk1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yo1sggk1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-735037232580"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"